blank_issues_enabled: false
contact_links:
  - name: strands-compose-agentcore Discussions
    url: https://github.com/strands-compose/bedrock-agentcore/discussions
    about: Please ask and answer questions here
  - name: strands-compose-agentcore Documentation
    url: https://github.com/strands-compose/bedrock-agentcore/tree/main/examples
    about: Visit the examples for help
